# Generated by Django 3.2.7 on 2021-11-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_platforminvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforminvitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
