const TITLE = "TITLE";
const ASSIGNEE = "ASSIGNEE";
const STATUS_DONE = "STATUS_DONE";
const STATUS_NOT_DONE = "STATUS_NOT_DONE";
const UNASSIGNED = "UNASSIGNED";

const SORT_BY_MAP = { TITLE: 1, ASSIGNEE: 2 };
const FILTER_BY_MAP = { STATUS_DONE: 1, STATUS_NOT_DONE: 2, ASSIGNEE: 3 };

export {
  TITLE,
  ASSIGNEE,
  UNASSIGNED,
  STATUS_DONE,
  STATUS_NOT_DONE,
  SORT_BY_MAP,
  FILTER_BY_MAP,
};
